### ISSUE TITLE
feat: apply react-toast

### ISSUE THREAD

**Issue by shseok** [shseok/mztrees#12]
# react-toast

### why use React toast
1. user experience
2. accessibility

"A concise and intuitive way to communicate about application status and interactions."

**Comment by imjaglan** [comment]
Hey, I would love to add it

**Comment by shseok** [comment]
@imjaglan  hi! Would you like to contribute to the project?

**Comment by imjaglan** [comment]
Yeah

**Comment by shseok** [comment]
Wow great! The places where react-toast is needed in this project are the post writing page and post editing page. 
Currently, when a user writes or edits a post, the page is just moved.
At this time, simply displaying a success message will help UX. 
If you think there are more places where react-toast is needed, please let me know. @imjaglan 

![image](https://github.com/shseok/mztrees/assets/80726955/449b209c-a8c8-47c5-bd29-facc670b57c1)

**Comment by imjaglan** [comment]
Do i have to setup the backend ass well?, I've added all the env's but there app is not working properly. I've created the ToastProvider component if you can tell me the location of the file i can even add it directly.

**Comment by shseok** [comment]
The backend is a bit complicated to set up. Therefore, it is recommended to use a proxy.
1. Set up the server’s API with Proxy
- next.config.json
```
  rewrites: async () => {
    return [
      {
        source: "/api/:path*",
        destination: "https://api.mztrees.com/api/:path*",
      },
    ];
  },
```
2. Remove baseUrl from the file currently using fetch and use it as /api/...
- src/lib/client.ts (in get / post / patch /delete)
```
export const fetchClient = {
...
const response = await fetch(this.baseUrl.concat(url), {
-> const response = await fetch(url, {
...
}
```
- src/app/write/page.tsx
- src/app/write/edit/[id]/page.tsx
```
 await fetch(`${baseUrl}/api/items/urls`, {
 -> await fetch(`/api/items/urls`, {
```
3. Call the API directly from the server component.
- src/app/items/[id]/page.tsx
```
const itemData = await getItem(parseInt(id));
-> const res = await fetch(`https://api.mztrees.com/api/items/${id}`);
  const itemData = await res.json();
```
4. Currently, the login part does not work smoothly in development mode. So you need to comment out "checkIsLoggedIn" and test it.
- src/app/write/layout.tsx
```
  const isLoggedIn = await checkIsLoggedIn();
  if (!isLoggedIn) {
    return redirect(`/login?next=/write`);
  }
  -> 
    // const isLoggedIn = await checkIsLoggedIn();
  // if (!isLoggedIn) {
  //   return redirect(`/login?next=/write`);
  // }
```

The location of the files to add is as follows:
- src/app/write/intro/page.tsx > in onSubmit
- src/app/write/edit/[id]/intro/page.tsx > in onSubmit


thank you
