### ISSUE TITLE
feat: Add One-time pop-up

### ISSUE THREAD

**Issue by shseok** [shseok/mztrees#16]
### One-time pop-up

A pop-up window that appears only once during a certain period of time when you visit a homepage is often called a “one-time pop-up” or “one-time modal.” These pop-up windows are used to deliver promotions, notices, cautions, etc. to users.

These one-time pop-ups are usually implemented by utilizing client-side storage such as cookies or local storage to prevent the visiting user from displaying the pop-up again if he or she has already seen the pop-up. This improves user experience and reduces the inconvenience of repetitive pop-up windows.

**We would like to use it for announcements so that users can report inconveniences or improvements to the service.**

For example, if there is no tag for the post you want and you want to add a tag, the method and link will be delivered in a one-time pop-up announcement.

**Comment by imjaglan** [comment]
I'll work on this

**Comment by shseok** [comment]
## Screenshot
![제목 없음](https://github.com/shseok/mztrees/assets/80726955/fbdbb4f9-6271-4cfe-b226-d700c50a5df6)


## Explanation

I would like to briefly show the contents in a small pop-up form at the bottom left.

I will explain the letters starting from the top.
```
Announcement

- If you find any inconvenience or bug while using the service, please report it and we will review it and respond quickly.
- If the desired post does not have a tag and you would like to add a tag, please click the icon below and use it.

icons on the left / “Stop watching today” + checkbox on the right
```
## main function

1. If the user checks the “Stop viewing for today” checkbox and presses the X button, the user will not see the pop-up for a day.

2. Users can click each icon to go to the link and communicate with the developer.
    - Email: Send content to the developer’s Google email
    - GitHub: Go to the issues tab in the repository.
    
---- 
@imjaglan

**Comment by imjaglan** [comment]
I've build the functionality just finishing the Ui, Sorry for the delay. I'm not able to figure out the icon library we are using can you tell me?

**Comment by shseok** [comment]
It's okay to be late.

I am not using a icon library, but I am using a SVG image.
Are the svg files currently needed close and checkbox?
Please let me know the svg you need so I can add it. 

Alternatively, you can use it by adding it to ``public/assets`` and exporting it to ``src/components/vectors``.
- If you want to add an svg file, delete the ``width`` and ``height`` inside and add ``fill="currentColor"``.
- currently close.svg is being used. Look at the usage process and apply it.

@imjaglan
